version: '3'

services:
  pet-superstore-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: neelypatel/pet-superstore-api
    container_name: pet-superstore-api
    environment:
      - HELLO=$HELLO
    ports:
      - "3000:3000"
